from __future__ import annotations


MAX_EXTERNAL_HTTP_RESPONSE_BODY_BYTES = 1_048_576
MAX_EXTERNAL_HTTP_JSON_DEPTH = 12
MAX_EXTERNAL_HTTP_JSON_FIELDS = 1_000
MAX_EXTERNAL_HTTP_JSON_ARRAY_ITEMS = 1_000
MAX_EXTERNAL_HTTP_JSON_STRING_LENGTH = 16_384
MAX_EXTERNAL_CATALOG_PRODUCTS_PER_PAGE = 100
MAX_EXTERNAL_DELIVERY_ITEMS = 100
MAX_EXTERNAL_DELIVERY_ITEM_LENGTH = 512
MAX_EXTERNAL_DELIVERY_MESSAGE_LENGTH = 1024
MAX_EXTERNAL_DELIVERY_CONTENT_LENGTH = 3500
