"""跨领域服务。"""

from app.services.audit import AuditLogService, AuditLogSummary
from app.services.business_plugins import (
    BUSINESS_PLUGIN_KIND_ADMIN_WEB_PANEL,
    BUSINESS_PLUGIN_KIND_BACKGROUND_JOB,
    BUSINESS_PLUGIN_KIND_BOT_FEATURE,
    BUSINESS_PLUGIN_KIND_EXTERNAL_SOURCE,
    BUSINESS_PLUGIN_KIND_PAYMENT,
    BUSINESS_PLUGIN_KIND_TENANT_TOOL,
    BUSINESS_PLUGIN_KIND_WEBHOOK_HANDLER,
    BUSINESS_PLUGIN_KINDS,
    BusinessPluginManifest,
    BusinessPluginRegistry,
    external_source_summary_to_plugin_manifest,
    is_plugin_entrypoint_allowed,
    list_current_business_plugin_manifests,
    payment_summary_to_plugin_manifest,
)
from app.services.external_sources import (
    ExternalCatalogSyncResult,
    ExternalCatalogSyncService,
    ExternalCatalogProvider,
    ExternalDeliveryProvider,
    ExternalDeliveryProviderWithContext,
    ExternalOrderProvider,
    ExternalOrderProviderWithContext,
    ExternalOrderOperationService,
    ExternalProviderNotRegisteredError,
    ExternalSourceOperationContext,
    ExternalSourceConnectionService,
    ExternalSourceConnectionSummary,
    ExternalSourceRuntimeCredentials,
    ExternalSourceProvider,
    SyncedExternalProduct,
)
from app.services.inventory import InventoryService, LockedInventory
from app.services.ledger import LedgerBalanceAudit, LedgerService, SettlementPolicySummary
from app.services.order_diagnostics import (
    OrderDeliveryDiagnostic,
    OrderDiagnosticsService,
    OrderDiagnosticsSummary,
    OrderExternalFulfillmentDiagnostic,
    OrderPaymentCallbackDiagnostic,
    OrderPaymentDiagnostic,
)
from app.services.orders import CreatedOrder, OrderService
from app.services.reports import ExportJobSummary, ReportExportService
from app.services.risk import (
    AfterSaleSummary,
    DisputeSummary,
    OrderCreationRiskBlocked,
    RiskActionResult,
    RiskControlService,
)
from app.services.supply import CreatedResellerProduct, CreatedSupplierOffer, SupplyService

__all__ = [
    "AuditLogService",
    "AuditLogSummary",
    "AfterSaleSummary",
    "BUSINESS_PLUGIN_KIND_ADMIN_WEB_PANEL",
    "BUSINESS_PLUGIN_KIND_BACKGROUND_JOB",
    "BUSINESS_PLUGIN_KIND_BOT_FEATURE",
    "BUSINESS_PLUGIN_KIND_EXTERNAL_SOURCE",
    "BUSINESS_PLUGIN_KIND_PAYMENT",
    "BUSINESS_PLUGIN_KIND_TENANT_TOOL",
    "BUSINESS_PLUGIN_KIND_WEBHOOK_HANDLER",
    "BUSINESS_PLUGIN_KINDS",
    "BusinessPluginManifest",
    "BusinessPluginRegistry",
    "CreatedOrder",
    "CreatedResellerProduct",
    "CreatedSupplierOffer",
    "DisputeSummary",
    "ExternalCatalogSyncResult",
    "ExternalCatalogSyncService",
    "ExternalCatalogProvider",
    "ExternalDeliveryProvider",
    "ExternalDeliveryProviderWithContext",
    "ExternalOrderProvider",
    "ExternalOrderProviderWithContext",
    "ExternalOrderOperationService",
    "ExternalProviderNotRegisteredError",
    "ExternalSourceOperationContext",
    "ExternalSourceConnectionService",
    "ExternalSourceConnectionSummary",
    "ExternalSourceRuntimeCredentials",
    "ExternalSourceProvider",
    "ExportJobSummary",
    "InventoryService",
    "LedgerBalanceAudit",
    "LedgerService",
    "LockedInventory",
    "OrderService",
    "OrderDeliveryDiagnostic",
    "OrderDiagnosticsService",
    "OrderDiagnosticsSummary",
    "OrderExternalFulfillmentDiagnostic",
    "OrderPaymentCallbackDiagnostic",
    "OrderPaymentDiagnostic",
    "OrderCreationRiskBlocked",
    "ReportExportService",
    "RiskActionResult",
    "RiskControlService",
    "SettlementPolicySummary",
    "SyncedExternalProduct",
    "SupplyService",
    "external_source_summary_to_plugin_manifest",
    "is_plugin_entrypoint_allowed",
    "list_current_business_plugin_manifests",
    "payment_summary_to_plugin_manifest",
]
